#ifndef INSERTSORT_GLOBAL_H
#define INSERTSORT_GLOBAL_H

#if defined(INSERTSORT_LIBRARY)
#  define INSERTSORTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define INSERTSORTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // INSERTSORT_GLOBAL_H
